# .platform/routes.yaml

# Route for the www subdomain
"https://www.{default}/":
    type: upstream
    upstream: "app:http"  # Routes traffic to the 'app' service on the 'http' port

# Route for the non-www subdomain (redirects to www)
"https://{default}/":
    type: redirect
    to: "https://www.{default}/"  # Redirects non-www traffic to the www subdomain
